### ISSUE TITLE
Maplibre support

### ISSUE THREAD

**Issue by m0nac0** [andrea689/mapbox-gl-dart#11]
Thank you for your great work on this plugin!
I'd like to make it work with [maplibre-gl-js](https://github.com/maplibre/maplibre-gl-js), an open source fork of mapbox-gl-js. However, I'm a bit lost on how to start. 
Is the code in this plugin generated somehow? Or do you have an idea of what would need to be changed to support maplibre? (Apart from the name, the API of maplibre should be identical to mapbox in the initial release.)

**Comment by arxarinze** [comment]
go checkout js interop library for dart. https://github.com/matanlurey/dart_js_interop

**Comment by m0nac0** [comment]
Thank you! I'm aware that package:js is used to process the `@JS()` annotations. I was wondering if all the classes annotated with `@JS()` are also generated (e.g. from the Mapbox GL JS Api), but I guess they were coded by hand.

Anyways, I got it to work for now just by swapping the mapbox js for maplibre js.

**Comment by andrea689** [comment]
Hi @m0nac0, yes I coded all by hand.. I don't know tools for generate it.
