### ISSUE TITLE
Feature id should not be num but dynamic

### ISSUE THREAD

**Issue by felix-ht** [andrea689/mapbox-gl-dart#14]
Feature ids are  currently of type num

`num get id => jsObject.id;`

It would be great if we could change that to be dynamic. As this aligns it with how id is defined for IOS and android.

This is how it is defined in iOS and android 
https://docs.mapbox.com/ios/maps/api/6.3.0/Protocols/MGLFeature.html#/c:objc(pl)MGLFeature(py)identifier

geojson-types also specifies it as` id?: number | string `

https://github.com/mapbox/geojson-types/blob/master/index.js

**Comment by andrea689** [comment]
Hi @felix-ht, I tried to use dynamic, but it seems mapbox-gl.js only accepts numbers.

If I print the id on click, a feature with numeric id is printed, the one with id string is printed null.

**Comment by andrea689** [comment]
you can try this branch: https://github.com/andrea689/mapbox-gl-dart/tree/feature-id-as-dynamic

- run examples `webdev serve example:8081`
- open http://localhost:8081/popup_on_click/index.html
- click theatre markers and see browser js console

**Comment by felix-ht** [comment]
i checked and it seems that this is an upstream issue:
https://github.com/mapbox/mapbox-gl-js/issues/2716

however adding promote id to the creation of the layer allows promoting an id that is part of the feature.properties - this works with strings as well.

Not strings
https://jsbin.com/gubadidaze/edit?html,console,output

Working with promotion
https://jsbin.com/jurocewunu/edit?html,console,output

So i would suggest to change id to dynamic anyhow. As this would allow to the use of promoteId to have string ids.

**Comment by felix-ht** [comment]
promoteId seems work fine with dart as well - https://github.com/Ocell-io/mapbox-gl-dart/tree/test-promoteId - (GeoJsonSource doesn’t contain the promoteId api)

**Comment by andrea689** [comment]
@felix-ht I also added `promoteId`, thank you!

**Comment by felix-ht** [comment]
Thanks for adding this 👍
