### ISSUE TITLE
pls！This package support flutter_web？

### ISSUE THREAD

**Issue by Mecil9** [andrea689/mapbox-gl-dart#5]

**Comment by andrea689** [comment]
This package is used by https://github.com/tobrun/flutter-mapbox-gl

And this is the PR for add flutter web compatibility:
https://github.com/tobrun/flutter-mapbox-gl/pull/223

**Comment by Mecil9** [comment]
> This package is used by https://github.com/tobrun/flutter-mapbox-gl
> 
> And this is the PR for add flutter web compatibility:
> [tobrun/flutter-mapbox-gl#223](https://github.com/tobrun/flutter-mapbox-gl/pull/223)

thx, i c it. i have another qus: how to change the map to custom-style map ?

**Comment by aardrop** [comment]
@Mecil9 did you ever find the solution to custom styling?
